basic_settings:
  site_title:  Begegnungen Burgdorf
#  favicon_image: /images/favicon.png

header_settings:
  # logo_image: /images/orig_logo.png
  logo_image: images/orig_logo.jpg
  logo_width: 50  # phone
  logo_width_tablet: 100
  logo_width_tablet_large: 100
  logo_width_laptop: 50
  logo_width_desktop: 200
  margin_top_phone: 20
  margin_top_tablet: 30
  margin_top_tablet_large: 30
  margin_top_laptop: 50
  margin_top_desktop: 50

break_settings:
  break_phonel: 480px
  break_tabletp: 767px
  break_tabletl: 1024px
  break_laptop: 1220px
  break_desktop: 1420px

menu_settings:
  menu_items:
    - title: 'Begegnungen'
      url: '/'
    - title: 'Angebot'
      url: 'angebot'
    - title: 'Therapeutinnen'
      url: '/therapeutinnen/'
    - title: 'Räumlichkeiten'
      url: 'rauemlichkeiten'
    - title: 'Erster Besuch'
      url: 'ersterbesuch'
    - title: 'Kontakt'
      url: 'kontakt'
  footer_menu_items:
    - title: 'Datenschutz'
      url: 'datenschutz'
    - title: 'AGB'
      url: 'agb'
    - title: 'Impressum'
      url: 'impressum'
  margin_top_phone: 20
  margin_top_tablet: 20
  margin_top_tablet_large: 20
  margin_top_laptop: 20
  margin_top_desktop: 5

footer_settings:
  logo_image: images/footer_logo.png
  logo_width: 38
  footer_tagline:

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  header_background_color: '#BFCF94'
  background_alt_color: '#f4f5f6'
  # text_dark_color: '#2A2F36'
  text_dark_color: '#738276'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  # accent_color: '#F2784B'
  accent_color: '#8f9779'
  border_color: '#dddddd'
  overlay_background_color: '#BFCF94'
  # overlay_text_color: '#ffffff'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  # h1_font_color: '#4d5d53'
  h1_font_color: '#738276'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
